# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: short-git-version-hash-extractor@1
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'richwalkman/apsifront'
    command: 'buildAndPush'
    Dockerfile: './frontend/dockerfile'
    buildContext: './frontend'
    tags: |
      $(Build.SourceVersion)
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'richwalkman/apsibackend'
    command: 'buildAndPush'
    Dockerfile: './backend/apsi_backend/Dockerfile.prod'
    buildContext: './backend/apsi_backend'
    tags: |
      $(Build.SourceVersion)